name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Rust Android targets
      run: |
        rustup target add aarch64-linux-android
        rustup target add armv7-linux-androideabi
        rustup target add i686-linux-android
        rustup target add x86_64-linux-android

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android SDK components
      run: |
        sdkmanager "platform-tools" "platforms;android-33" "platforms;android-24" "build-tools;33.0.0" "ndk;25.1.8937393"

    - name: Set Android environment variables
      run: |
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.1.8937393" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm ci

    - name: Install Tauri CLI
      run: npm install -g @tauri-apps/cli

    - name: Initialize Tauri Android
      run: npm run tauri:android:init

    - name: Build Android APK (Debug)
      run: npm run tauri:android:build -- --debug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: android-debug-apk
        path: src-tauri/gen/android/app/build/outputs/apk/debug/*.apk
        retention-days: 30

    - name: Build Android APK (Release)
      run: npm run tauri:android:build
      continue-on-error: true  # Release может не собраться без ключа подписи

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: android-release-apk
        path: src-tauri/gen/android/app/build/outputs/apk/release/*.apk
        retention-days: 30

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src-tauri/gen/android/app/build/outputs/apk/debug/*.apk
          src-tauri/gen/android/app/build/outputs/apk/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
